# Generated by Django 4.0.4 on 2022-05-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_room_topic_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
    ]
